version: 2

run:
  timeout: 5m

linters:
  enable:
    - lll
    - mnd

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - lll 